# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'theoolWallet.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plug(object):
    def setupUi(self, plug):
        plug.setObjectName("plug")
        plug.resize(396, 84)
        self.PlugText = QtWidgets.QLabel(plug)
        self.PlugText.setGeometry(QtCore.QRect(90, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setItalic(True)
        self.PlugText.setFont(font)
        self.PlugText.setObjectName("PlugText")

        self.retranslateUi(plug)
        QtCore.QMetaObject.connectSlotsByName(plug)

    def retranslateUi(self, plug):
        _translate = QtCore.QCoreApplication.translate
        plug.setWindowTitle(_translate("plug", "Dialog"))
        self.PlugText.setText(_translate("plug", "Under Constraction"))
